name: Test AIBOM Bedrock

on:
  push:
    branches: [main]

jobs:
  aibom-bedrock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Generate AIBOM from AWS Bedrock
        uses: Vickydew1/xbom-action@main
        with:
          bom-type:              aibom
          aibom-source:          bedrock
          aws-region:            us-east-1
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          token:                 ${{ secrets.ACCUKNOX_TOKEN }}
          endpoint:              ${{ secrets.ACCUKNOX_ENDPOINT }}
          label:                 ${{ secrets.ACCUKNOX_LABEL }}
          project-name:          Action
          project-classifier:    application
