name: AccuKnox Secret Scan
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: accuknox/secret-scan-action-new@latest
        with:
          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          accuknox_endpoint: cspm.stage.accuknox.com
          accuknox_label: GVD
          soft_fail: true
